---
- name: Install HTTP server
  hosts: n1
  become: yes

  tasks:
  - name: Install HTTPD
    dnf:
      name: httpd
      state: present
    when: ansible_distribution == "Amazon" or ansible_distributioon == "Centos"

  - name: Start Httpd
    service:
      name: httpd
      state: started 
    when: ansible_distribution == "Amazon" or ansible_distributioon == "Centos"
  
  - name: Enable Httpd
  service: 
    name: httpd
    enabled: yes
  when: ansible_distribution == "Amazon" or ansible_distributioon == "Centos"

  - name: Install Apache2
    apt:
      name: apache2
      state: present
    when: ansible_distribution == "Ubuntu" or ansible_distributioon == "Debian"

  - name: Start Apache2
    service:
      name: apache2
      state: started
    when: ansible_distribution == "Ubuntu" or ansible_distributioon == "Debian"

  - name: Enable Apache2
  service:
    name: apache2
    enabled: yes
  when: ansible_distribution == "Ubuntu" or ansible_distributioon == "Debian"
...