---
- name: Variables Demo
  hosts: g1
  become: yes
  vars: 
    myusername: atete white

  tasks:
  - name: Update Dynamic page
    template:
      src: dynamic.j2
      dest: /var/www/html/dynamic.html 
      force: yes
...      